### ISSUE TITLE
youtube works but Netflix does not

### ISSUE THREAD

**Issue by ljdomingues** [nigelb/Static-UPnP#3]
Nigel,
I am using you you deamon. 
Works great for youtube on iOS, Android and chrome browser.
The Android and the iOS Netflix app do not work. Does not even show the cast icon.
Netflix works well on chrome, though!
Is this a known issue?
thanks,
Leo

**Comment by nigelb** [comment]
Hi Leo,

Sorry I have been away, I just replicated your issue with my Android phone. The Chromecast also does not show up in the Google Home App when I do a device scan, but it totally shows up in the Youtube App.

Very Strange.

I will have to play with it and see if I can find a fix.

Thanks,

Nigel.

**Comment by ljdomingues** [comment]
Nigel,
thanks for coming back to me on this.
I did some debugging with wireshark and what I see is that netflix in no longer using SSTP/DIAL. It is only using mDNS!
I think that is the reason why your code is no longer working.
Maybe you can confirm that as well...
Leo

**Comment by nigelb** [comment]
Hi Leo,

Yeah I did notice it trying mDNS, I am having a look to see if I can respond to the mDNS as well.

If you can add entries to your local DNS server something like [this](http://www.github.com/miselin/mDNS-Unicast-Lookup) may help but I haven't got it working for me correctly yet.

Thanks,

Nigel.

**Comment by nigelb** [comment]
Hi Leo,

Have a look at the mdns branch. It now responds to multicast DNS requests.

Thanks,
Nigel.

**Comment by nigelb** [comment]
You will need to update your config files if you have modified them.

**Comment by nigelb** [comment]
Merged with master

**Comment by ljdomingues** [comment]
Thanks. I will test and let you know.
