### ISSUE TITLE
Problem with Unicode characters

### ISSUE THREAD

**Issue by cajonKA** [nigelb/Static-UPnP#5]
My chromcast has unicode chars in its name.
Therefore the get the errormessage
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 4: ordinal not in range(128)

**Comment by cajonKA** [comment]
I fixed it in my version by adding 
`.encode('utf-8')`
at the end of line 65 in the file
**StaticUPnP_StaticServices.py**

**Comment by nigelb** [comment]
I have updated the get_chromecast_friendly_name function to encode the output as UTF-8.
